name: Update Download Stats

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

env:
  GitHubMail: "ascpbot128@gmail.com"
  GitHubName: "TheASCPBot"
  GitHubToken: ${{ secrets.GH_TOKEN }}

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python .github/scripts/update_download_stats.py

      - name: Check for changes
        run: |
          echo "Content of API/download_stats.json after script run:"
          cat API/download_stats.json
          git status
          git diff API/download_stats.json

      - name: Commit and push changes
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global color.ui true
          git config --global credential.helper store
          echo "https://${GitHubName}:${GitHubToken}@github.com" > ~/.git-credentials
          git add API/download_stats.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(stats): Update device download counts"
            git push
          fi
